### ISSUE TITLE
Viewing diffs for a package with update fails

### ISSUE THREAD

**Issue by ftsell** [ericm/yup#11]
I recently tried out yup and just used it do do updates.

After printing the PKGBUILD of a package which has an available update it asks me what to do. I chose _see Diff_ by pressing `D` after which it generated the following output:

```
==> View, see Diffs or Edit the PKGBUILD? (All or None): D
fatal: ambiguous argument '@~..@': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
==> Continue?:
```

It should be noted that the directory yup tries to do the diff in was previously managed by _yay_ as that is my current main package manager.

**Comment by ericm** [comment]
I'll look into this

**Comment by ericm** [comment]
Could you show me some steps to reproduce this?

**Comment by Atemu** [comment]
Could it be that this happens when there is no difference? (version bump or automatic version bump from -git package)

**Comment by ericm** [comment]
I've reinstalled packages before and never got that message. What package were you syncing?

**Comment by Atemu** [comment]
Reinstalling works for me too, it just shows nothing instead of the diff, ~~have you tried upgrading from an older version?~~

One package I just had this error with was upgrading https://aur.archlinux.org/packages/based-connect-git/, I had a few others aswell but those are too far back in the terminal buffer now and I don't remember which ones. Is there a log somewhere maybe?

~~Anyways, this was just a hunch because I never saw an empty diff while upgrading a bunch of -git packages that `yay` didn't even notice (nice one `yup`!) and bumps with no changes should be quite common.~~

Just found out how to repro, try to install packages like based-connect-git without it being present in the yup cache.  
It works for some and not for others (works for auracle-git for example. It shows the diff of the commit you're trying to install vs. the commit before it in the AUR git repo btw, not the commit of the currently installed version, is this intended?).  
There is only one commit for based-connect-git in the AUR git repo, maybe that has something to do with it.

**Comment by ericm** [comment]
> There is only one commit for based-connect-git in the AUR git repo, maybe that has something to do with it.
That's it i'd say. `git diff @~..@`  only works on branches with multiple commits. I'll just add a command error check in the next update.
