### ISSUE TITLE
Hangs at checking for dependencies during update?

### ISSUE THREAD

**Issue by marek-lach** [ericm/yup#29]
OS: **EndeavourOS**
When doing an AUR update with `yup -Syua`, the `checking for dependencies` takes a very long time, so I usually stop it, as there are no signs of progress whatsoever even after 30-45 minutes.

Does yup usually check for dependencies of all the updating applications at once, or one by one?

Figuring out which packages from the AUR need to be updated on my system works just fine:

![step1yup](https://user-images.githubusercontent.com/45913977/78554953-60f79380-780c-11ea-9f7f-18556ef4967b.png)

2. But after that, yup seems to either hang, or perhaps should I wait for such a long time?
![step2yup2hangs](https://user-images.githubusercontent.com/45913977/78555045-85ec0680-780c-11ea-8284-6eb7f2c55744.png)

**Comment by ericm** [comment]
This appears to be a persisting issue with all packages.

**Comment by ericm** [comment]
The issue was that I had previously implemented a conflict checker to ask if you wanted to uninstall a conflicting package, but it didn't take into account that checking this means that if the package is already installed, it'll come up as a conflict so it just hung there waiting for user input. My apologies.
