### ISSUE TITLE
Add support for Page Up, Page Down, Home, End keys

### ISSUE THREAD

**Issue by bhhenry** [ericm/yup#43]
## Are you on latest version of yup?
Yes

## Steps to Reproduce the Problem

  1. run yup
  2. press page up key

## Other Details
Some of us old timers still use those keys. They are right there above the arrow keys on my Model M, and can come in quite handy.

**Comment by Ballasi** [comment]
I like that idea, as someone who uses these keys often they do come in handy!

I sent a PR adding this feature in #45 if you want to try this out.

I wasn't sure if it was best to use HOME or END to return to the bottom of the stack, I personally see HOME as "go at the very top" and END as "go at the very bottom", since the first element of the search is at the bottom, I just used END as going back there. It felt more comfortable using this on my side.
